# Generated by Django 5.1.1 on 2024-10-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_ejecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecutivo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivos', to='page.sucursal'),
        ),
    ]
