# Generated by Django 5.0.4 on 2024-05-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
