# Generated by Django 5.0.4 on 2024-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='marcas/')),
                ('industria', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
